// AUTOGENERATED FILE: DO NOT EDIT (idlc v0.2.0)
#pragma once

#include <stdint.h>
#include "object.h"

typedef Object IRPMBService;

#define IRPMBService_ERROR_RPMB_MAC INT32_C(10)
#define IRPMBService_ERROR_RPMB_WRITE_COUNTER INT32_C(11)
#define IRPMBService_ERROR_RPMB_ADDR INT32_C(12)
#define IRPMBService_ERROR_RPMB_WRITE INT32_C(13)
#define IRPMBService_ERROR_RPMB_READ INT32_C(14)
#define IRPMBService_ERROR_RPMB_NOT_PROVISIONED INT32_C(15)
#define IRPMBService_ERROR_RPMB_MAC_GENERATION INT32_C(16)
#define IRPMBService_ERROR_RPMB_RNG_GENERATION INT32_C(17)
#define IRPMBService_ERROR_RPMB_NONCE INT32_C(18)
#define IRPMBService_ERROR_RPMB_PROVISIONED INT32_C(19)

#define IRPMBService_OP_rpmbProvisionKey 0
#define IRPMBService_OP_rpmbErase 1
#define IRPMBService_OP_rpmbCheckProv 2
#define IRPMBService_OP_rpmbRead 3
#define IRPMBService_OP_rpmbWrite 4

static inline int32_t
IRPMBService_release(Object self)
{
    return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IRPMBService_retain(Object self)
{
    return Object_invoke(self, Object_OP_retain, 0, 0);
}

/*
*
*  Provision the RPMB authentication key.
*
*  This is a one-time, irreversible operation.  Once the key is
*  provisioned it cannot be changed or erased.
*
*  Operation code: 0 — MUST remain the first method.
*
*  @param[in] keyType
*    0 — Provision the production (OEM) key.
*    1 — Provision a test key (for development/validation only).
*
*  @return
*  Object_OK                             — key provisioned successfully.
*  IRPMBService_ERROR_RPMB_PROVISIONED   — key already provisioned.
*  Object_ERROR_INVALID                  — unsupported keyType value.
*  Object_ERROR                          — provisioning failed.
*
*/
static inline int32_t IRPMBService_rpmbProvisionKey(Object self, int32_t keyType_val)
{
    ObjectArg a[] = {
        {.b = (ObjectBuf) { &keyType_val, sizeof(int32_t) } },
    };

    int32_t result = Object_invoke(self, IRPMBService_OP_rpmbProvisionKey, a, ObjectCounts_pack(1, 0, 0, 0));

    return result;
}

/*
*
*  Erase the entire RPMB partition.
*
*  All data stored in the RPMB partition is permanently destroyed.
*  The RPMB authentication key must already be provisioned before
*  this operation can succeed.
*
*  Operation code: 1 — MUST remain the second method.
*
*  @return
*  Object_OK                    — partition erased successfully.
*  IRPMBService_ERROR_RPMB_WRITE — erase (write) operation failed.
*  Object_ERROR                 — generic failure.
*
*/
static inline int32_t IRPMBService_rpmbErase(Object self)
{
    return Object_invoke(self, IRPMBService_OP_rpmbErase, 0, 0);
}

/*
*
*  Check whether the RPMB authentication key has been provisioned and
*  is valid.
*
*  Operation code: 2 — MUST remain the third method.
*
*  @return
*  Object_OK                              — key is provisioned and MAC is valid.
*  IRPMBService_ERROR_RPMB_NOT_PROVISIONED — key has not been provisioned.
*  IRPMBService_ERROR_RPMB_MAC            — key provisioned but MAC mismatch.
*
*/
static inline int32_t IRPMBService_rpmbCheckProv(Object self)
{
    return Object_invoke(self, IRPMBService_OP_rpmbCheckProv, 0, 0);
}

/*
*
*  Read one or more 256-byte blocks from the RPMB partition.
*
*  The RPMB service performs the full authenticated read protocol:
*  nonce generation, HMAC verification on the device response, and
*  write-counter validation.  The caller receives only the plaintext
*  data payload.
*
*  Operation code: 3 — extended method, not present in original TA.
*
*  @param[in]  address     Half-sector address of the first block to read.
*  @param[in]  blockCount  Number of 256-byte blocks to read (≥ 1).
*  @param[out] data        Caller-supplied buffer; must be at least
*                          blockCount × 256 bytes.
*
*  @return
*  Object_OK                              — read succeeded; data is valid.
*  IRPMBService_ERROR_RPMB_NOT_PROVISIONED — key not provisioned.
*  IRPMBService_ERROR_RPMB_READ           — device returned a read error.
*  Object_ERROR                           — generic IPC or internal failure.
*
*/
static inline int32_t IRPMBService_rpmbRead(Object self, uint32_t address_val, uint32_t blockCount_val, void *data_ptr, size_t data_len, size_t *data_lenout)
{
    struct bi {
        uint32_t m_address;
        uint32_t m_blockCount;
    } i;

    i.m_address = address_val;
    i.m_blockCount = blockCount_val;
    ObjectArg a[] = {
        {.b = (ObjectBuf) { &i, 8 } },
        {.b = (ObjectBuf) { data_ptr, data_len * sizeof(uint8_t) } },
    };

    int32_t result = Object_invoke(self, IRPMBService_OP_rpmbRead, a, ObjectCounts_pack(1, 1, 0, 0));

    *data_lenout = a[1].b.size / sizeof(uint8_t);
    return result;
}

/*
*
*  Write one or more 256-byte blocks to the RPMB partition.
*
*  The RPMB service performs the full authenticated write protocol:
*  write-counter fetch, HMAC computation over the write frame, and
*  result-frame verification after the write.
*
*  Operation code: 4 — extended method, not present in original TA.
*
*  @param[in] address     Half-sector address of the first block to write.
*  @param[in] blockCount  Number of 256-byte blocks to write (≥ 1).
*  @param[in] data        Data to write; must be exactly blockCount × 256 bytes.
*
*  @return
*  Object_OK                              — write succeeded.
*  IRPMBService_ERROR_RPMB_NOT_PROVISIONED — key not provisioned.
*  IRPMBService_ERROR_RPMB_WRITE          — device returned a write error.
*  Object_ERROR                           — generic IPC or internal failure.
*
*/
static inline int32_t IRPMBService_rpmbWrite(Object self, uint32_t address_val, uint32_t blockCount_val, const void *data_ptr, size_t data_len)
{
    struct bi {
        uint32_t m_address;
        uint32_t m_blockCount;
    } i;

    i.m_address = address_val;
    i.m_blockCount = blockCount_val;
    ObjectArg a[] = {
        {.b = (ObjectBuf) { &i, 8 } },
        {.bi = (ObjectBufIn) { data_ptr, data_len * sizeof(uint8_t) } },
    };

    int32_t result = Object_invoke(self, IRPMBService_OP_rpmbWrite, a, ObjectCounts_pack(2, 0, 0, 0));

    return result;
}

